/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkoutsRouteImport } from './routes/_app.workouts'
import { Route as AppTitlesRouteImport } from './routes/_app.titles'
import { Route as AppMealsRouteImport } from './routes/_app.meals'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCupRouteImport } from './routes/_app.cup'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppBodyRouteImport } from './routes/_app.body'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutsRoute = AppWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AppRoute,
} as any)
const AppTitlesRoute = AppTitlesRouteImport.update({
  id: '/titles',
  path: '/titles',
  getParentRoute: () => AppRoute,
} as any)
const AppMealsRoute = AppMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCupRoute = AppCupRouteImport.update({
  id: '/cup',
  path: '/cup',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBodyRoute = AppBodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/body': typeof AppBodyRoute
  '/calendar': typeof AppCalendarRoute
  '/cup': typeof AppCupRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/meals': typeof AppMealsRoute
  '/titles': typeof AppTitlesRoute
  '/workouts': typeof AppWorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/body': typeof AppBodyRoute
  '/calendar': typeof AppCalendarRoute
  '/cup': typeof AppCupRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/meals': typeof AppMealsRoute
  '/titles': typeof AppTitlesRoute
  '/workouts': typeof AppWorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/body': typeof AppBodyRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/cup': typeof AppCupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/meals': typeof AppMealsRoute
  '/_app/titles': typeof AppTitlesRoute
  '/_app/workouts': typeof AppWorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/body'
    | '/calendar'
    | '/cup'
    | '/dashboard'
    | '/leaderboard'
    | '/meals'
    | '/titles'
    | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/body'
    | '/calendar'
    | '/cup'
    | '/dashboard'
    | '/leaderboard'
    | '/meals'
    | '/titles'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/body'
    | '/_app/calendar'
    | '/_app/cup'
    | '/_app/dashboard'
    | '/_app/leaderboard'
    | '/_app/meals'
    | '/_app/titles'
    | '/_app/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workouts': {
      id: '/_app/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AppWorkoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/titles': {
      id: '/_app/titles'
      path: '/titles'
      fullPath: '/titles'
      preLoaderRoute: typeof AppTitlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meals': {
      id: '/_app/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AppMealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cup': {
      id: '/_app/cup'
      path: '/cup'
      fullPath: '/cup'
      preLoaderRoute: typeof AppCupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/body': {
      id: '/_app/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof AppBodyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBodyRoute: typeof AppBodyRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCupRoute: typeof AppCupRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMealsRoute: typeof AppMealsRoute
  AppTitlesRoute: typeof AppTitlesRoute
  AppWorkoutsRoute: typeof AppWorkoutsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBodyRoute: AppBodyRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCupRoute: AppCupRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMealsRoute: AppMealsRoute,
  AppTitlesRoute: AppTitlesRoute,
  AppWorkoutsRoute: AppWorkoutsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
